import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>어바웃 페이지</h1>
      <Link href='/'>
        <a style={{color: "pink"}}>메인</a>
      </Link>

      <Link href='/about'>
        <a style ={{color: "blue"}}>어바웃</a>
      </Link>
    </>
  )
}
